### ISSUE TITLE
Not working on Sb3

### ISSUE THREAD

**Issue by MatthD** [farcaller/DashDoc#59]
Hi,

The module is not working on Sublime-Text3 on Mac, I added { "keys": ["ctrl+d"], "command": "dash_doc" } to my keycap but it does not open at all :s

**Comment by mattbrictson** [comment]
I think this is a bug in Dash. I am using Dash for macOS 4.1.0 and Sublime Text 3 build 3152, and DashDoc no longer works for me either. It seemed to stop working when I recently upgraded to Dash 4.1.0.

**Comment by Kapeli** [comment]
This commit has broken things: https://github.com/farcaller/DashDoc/commit/73844f7be13f0eae0b1965f0e7b9012d79733c18.

The plugin is now calling `dash-plugin:keys=...&query=`. The URL scheme on macOS starts with `dash-plugin://`.

**Comment by j9ac9k** [comment]
bah; that was my pull request, I thought that was just being called on linux only platforms :(

**Comment by ocket8888** [comment]
Is there a temporary workaround? I assume somewhere in the package source I could just change the external call, right?

**Comment by j9ac9k** [comment]
Since the fix is adding two characters, easiest way would be just to add those characters yourself.  Locate the `DashDoc.py` file, and edit the last line of the file (line 70) so instead of reading `dash-plugin:keys=....`, it reads `dash-plugin://keys....`.

If you're not able to locate the file easily, I suggest you add the PackageResourceViewer package here: https://packagecontrol.io/packages/PackageResourceViewer

**Comment by ocket8888** [comment]
Perfect, works like a charm.

**Comment by j9ac9k** [comment]
glad to hear it, again apologies for the breakage!
